pipelines:
  test:
    blubberfile: blubber.yaml
    stages:
      - name: build-python3-executor
        build: build-python3-executor
        run: false
      - name: test-python3-executor
      - name: build-format-python3
        build: build-format-python3
        run: false
      - name: format-python3
      - name: build-javascript-executor
        build: build-javascript-executor
        run: false
      - name: test-javascript-executor
      - name: build
        build: build
        run: false
      - name: test
      - name: build-python3-all-evaluator
        build: build-python3-all-evaluator
        run: false
      - name: test-python3-all-evaluator
      - name: build-javascript-all-evaluator
        build: build-javascript-all-evaluator
        run: false
      - name: test-javascript-all-evaluator
    execution:
      - [build-python3-executor, test-python3-executor]
      - [build-format-python3, format-python3]
      - [build-javascript-executor, test-javascript-executor]
      - [build, test]
      - [build-python3-all-evaluator, test-python3-all-evaluator]
      - [build-javascript-all-evaluator, test-javascript-all-evaluator]
  publish:
    blubberfile: blubber.yaml
    stages:
      - name: test
        build: test
        run: true
      - name: production
        build: production
        publish:
          image:
            tags:
              - latest
              - '${setup.tag}'
      - name: build-and-publish-python3-all
        build: production-python3-all
        publish:
          image:
            name: wikimedia/mediawiki-services-function-evaluator-python3-all
            tags:
              - latest
      - name: build-and-publish-javascript-all
        build: production-javascript-all
        publish:
          image:
            name: wikimedia/mediawiki-services-function-evaluator-javascript-all
            tags:
              - latest
