pipelines:
  test:
    blubberfile: blubber.yaml
    stages:
      - name: build-python3-executor
        build: build-python3-executor
        run: false
      - name: test-python3-executor
      - name: build-javascript-executor
        build: build-javascript-executor
        run: false
      - name: test-javascript-executor
      - name: build
        build: build
        run: false
      - name: test
    execution:
      - [build-python3-executor, test-python3-executor] 
      - [build-javascript-executor, test-javascript-executor] 
      - [build, test] 
