pipelines:
  test:
    blubberfile: blubber.yaml
    stages:
      - name: build-python3-executor
        build: build-python3-executor
        run: false
      - name: test-python3-executor
      - name: build-format-python3
        build: build-format-python3
        run: false
      - name: format-python3
      - name: build-javascript-executor
        build: build-javascript-executor
        run: false
      - name: test-javascript-executor
      - name: build
        build: build
        run: false
      - name: test
    execution:
      - [build-python3-executor, test-python3-executor]
      - [build-format-python3, format-python3]
      - [build-javascript-executor, test-javascript-executor]
      - [build, test]
  publish:
    blubberfile: blubber.yaml
    stages:
      - name: test
        build: test
        run: true
      - name: production
        build: production
        publish:
          image:
            tags:
              - latest
              - '${setup.tag}'
